name: Docker CI

on:
  workflow_dispatch:
  schedule:
    - cron:  '33 3 * * 3'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get metadata
        id: get_metadata
        run: |
          curl -s https://api.github.com/repos/jagrosh/MusicBot/releases/latest > response
          TAG=$(jq -r '.tag_name' response)
          DL_URL=$(jq -r '.assets[0].browser_download_url' response)
          echo TAG=$TAG >> $GITHUB_OUTPUT
          echo DL_URL=$DL_URL >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/jmusicbot
          tags: |
            latest,enable=${{ github.ref_name == 'main' }}
            ${{ steps.get_metadata.outputs.tag }},enable=${{ github.ref_name == 'main' }}
            ${{ github.ref_name }},enable=${{ github.ref_name != 'main' }}
          labels: |
            org.opencontainers.image.version=${{ steps.get_metadata.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DL_URL=${{ steps.get_metadata.outputs.dl_url }}

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/jmusicbot
          readme-filepath: ./README.md
